version: '3.8'
services:
  web:
    build: .
    ports:
      - "${APP_PORT}:8080"  # Usa la variable de Jenkins
    environment:
      NODE_ENV: ci

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "${DB_PORT}:5432"