version: '3.8'
services:
  web:
    build: .
    ports:
      - "8081:8080"  # Puerto 8081 para desarrollo local (evita conflicto con Jenkins)
    environment:
      NODE_ENV: development

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"  # Puerto alternativo para la base de datos