version: '3.8'
services:
  web:
    build: .
    ports:
      - "8081:3000"  # Cambiado a 3000 porque es el puerto que usa React
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"